export const GET_ALL_SKETCH_PENDING = 'GET_ALL_SKETCH_PENDING';
export const GET_ALL_SKETCH_FULFILLED = 'GET_ALL_SKETCH_FULFILLED';
export const GET_ALL_SKETCH_REJECTED = 'GET_ALL_SKETCH_REJECTED';

export const GET_FAVS_PENDING = 'GET_FAVS_PENDING';
export const GET_FAVS_FULFILLED = 'GET_FAVS_FULFILLED';
export const GET_FAVS_REJECTED = 'GET_FAVS_REJECTED';